version: "3.3"
services:
  #  docker-registry:
  #    image: registry:2
  #    container_name: swiggy-docker-registry
  #    ports:
  #      - "5000:5000"
  #    restart: always
  #    volumes:
  #      - ./docker/volume:/var/lib/registry
  #
  #  docker-registry-ui:
  #    image: parabuzzle/craneoperator:latest
  #    ports:
  #      - "8082:8082"
  #    environment:
  #      - REGISTRY_HOST=docker-registry
  #      - REGISTRY_PORT=5000
  #      - REGISTRY_PROTOCOL=http
  #      - SSL_VERIFY=false
  #      - USERNAME=admin
  #      - PASSWORD=admin
  #    restart: always
  #    depends_on:
  #      - docker-registry

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swiggy
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

#  order-service:
#    image: swiggy/order-stervice
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - "8000:8000"
#
#  reverse-proxy:
#    image: nginx
#    container_name: reverse-proxy
#    volumes:
#      - ./docker-volumes/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"