version: "3.3"
services:
  database:
    # docker image tag d462573d8688 localhost:5000/database:latest
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food-order
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  order-service:
    # docker image tag 90b310a8b25e localhost:5000/order-service:master
    image: order-service:master
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8000:8000"
#
#  reverse-proxy:
#    image: nginx
#    container_name: reverse-proxy
#    volumes:
#      - ./docker-volumes/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"