mariadb:
  host: 192.168.33.10

server:
  timezone: Asia/Kolkata
  port: 8000
  tomcat:
    protocol-header: X-Forwarded-Proto
    connection-timeout: 60s
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  jetty:
    connection-idle-timeout: 1000ms

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE