mariadb:
  host: database

server:
  timezone: Asia/Kolkata
  port: 8000
  tomcat:
    protocol-header: X-Forwarded-Proto
    connection-timeout: 60s
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  jetty:
    connection-idle-timeout: 1000ms