version: "3.3"
services:
  docker-registry:
    image: registry:2
    ports:
      - "5000:5000"
    restart: always

    #
    #  docker-registry-ui:
    #    image: parabuzzle/craneoperator:latest
    #    ports:
    #      - "8082:8082"
    #    environment:
    #      - REGISTRY_HOST=docker-registry
    #      - REGISTRY_PORT=5000
    #      - REGISTRY_PROTOCOL=http
    #      - SSL_VERIFY=false
    #      - USERNAME=admin
    #      - PASSWORD=admin
    #    restart: always
    #    depends_on:
    #      - docker-registry